<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="vendeglatas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
            <xs:element name="Foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
            <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
            <xs:element name="Rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:key name="etterem_kulcs">
        <xs:selector xpath="Etterem"/>
        <xs:field xpath="@ekod"/>
    </xs:key>

    <xs:key name="foszakalcs_kulcs">
        <xs:selector xpath="Szakacs"/>
        <xs:field xpath="@Fkod"/>
    </xs:key>

    <xs:key name="gyakornok_kulcs">
        <xs:selector xpath="Gyakornok"/>
        <xs:field xpath="@GYkod"/>
    </xs:key>

    <xs:key name="vendeg_kulcs">
        <xs:selector xpath="Veneg"/>
        <xs:field xpath="@Vkod"/>
    </xs:key>

    <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
        <xs:selector xpath="rendeles"/>
        <xs:field xpath="@E_V_E"/>
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="vendeg_idegen_kulcs">
        <xs:selector xpath="rendeles"/>
        <xs:field xpath="@E_V_V"/>
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
        <xs:selector xpath="foszakacs"/>
        <xs:field xpath="@E_F"/>
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
        <xs:selector xpath="szakacs"/>
        <xs:field xpath="@E_SZ"/>
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
        <xs:selector xpath="gyakornok"/>
        <xs:field xpath="@E_GY"/>
    </xs:keyref>


<!--1:1 kapcsolathoz-->
    <xs:unique name="unique_foszakacs">
        <xs:selector xpath="foszakacs"/>
        <xs:field xpath="@e_f"/>
    </xs:unique>
</xs:element>

<!--Komplex tipusok definiálása-->
<xs:complexType name="etteremTipus">
    <xs:sequence>
    <xs:element name="nev" type="xs:string"/>
    <xs:element name="cim" type="cimTipus"/>
    <xs:element name="csillag" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="ekod" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="cimTipus">
    <xs:sequence>
        <xs:element name="varos" type="xs:string"/>
        <xs:element name="utca" type="xs:string"/>
        <xs:element name ="hazszam" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="foszakacsTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="eletkor" type="xs:integer"/>
        <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="szakacsTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="reszleg" type="xs:string"/>
        <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="szkod" type="xs:string" use="required"/>
    <xs:attribute name="e_sz" type="xs:string" use="required"/> 
</xs:complexType>

<xs:complexType name="gyakorlatTipus">
    <xs:sequence>
        <xs:element name="kezdete" type="xs:string"/>
        <xs:element name="idotartama" type="xs:string"/>
    </xs:sequence>
    <xs:attribute >
</xs:complexType>

<xs:complexType name="vendegTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="eletkor" type="xs:integer"/>
        <xs:element name="cim" type="cimTipus"/>
    </xs:sequence>
    <xs:attribute name="Vkod" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="rendelesTipus">
    <xs:sequence>
        <xs:element name="osszeg" type="xs:integer"/>
        <xs:element name="etel" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="e_v_e" type="xs:string" use="required"/>
    <xs:attribute name="e_v_v" type="xs:string" use="required"/>
</xs:complexType>


</xs:schema>