<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
                <xs:element name="Foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
                <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
                <xs:element name="Rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->
        <xs:key name="etterem_kulcs">
            <xs:selector xpath="Etterem"/>
            <xs:field xpath="@Ekod"/>
        </xs:key>

        <xs:key name="foszakalcs_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@Fkod"/>
        </xs:key>

        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@GYkod"/>
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="Vendeg"/>
            <xs:field xpath="@Vkod"/>
        </xs:key>

        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@E_V_E"/>
        </xs:keyref>

        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@E_V_V"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
            <xs:selector xpath="Szakacs"/>
            <xs:field xpath="@E_SZ"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@E_GY"/>
        </xs:keyref>


    <!--1:1 kapcsolathoz-->
        <xs:unique name="unique_foszakacs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:unique>
    </xs:element>

    <!--Komplex tipusok definiálása-->
    <xs:complexType name="etteremTipus">
        <xs:sequence>
        <xs:element name="Nev" type="xs:string"/>
        <xs:element name="Cim" type="cimTipus"/>
        <xs:element name="Csillag" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="Ekod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name ="Hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Fkod" type="xs:string" use="required"/>
        <xs:attribute name="E_F" type="xs:string" use="required"/> 
    </xs:complexType>

    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="Reszleg" type="xs:string"/>
            <xs:element name="Nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="SZkod" type="xs:string" use="required"/>
        <xs:attribute name="E_SZ" type="xs:string" use="required"/> 
    </xs:complexType>

    <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="Kezdete" type="xs:string"/>
            <xs:element name="Idotartam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Gyakorlat" type="gyakorlatTipus"/>
            <xs:element name="Muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="GYkod" type="xs:string" use="required"/>
        <xs:attribute name="E_GY" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="Vkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="xs:integer"/>
            <xs:element name="Etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="E_V_E" type="xs:string" use="required"/>
        <xs:attribute name="E_V_V" type="xs:string" use="required"/>
    </xs:complexType>


</xs:schema>